apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: sce06147/scg-2023:1f0e0b5f54a74d26ca6921af71a00d6d439aede9
          ports:
            - containerPort: 80
